[project]
name = "mayan-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "imap-client>=0.1.8",
    "langchain>=0.3.26",
    "langchain-ollama>=0.3.4",
    "langgraph>=0.5.2",
    "python-dotenv>=1.1.1",
]
